spring.application.name=OrdersMicroService
server.port=8422

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/shop}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:shop_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:shop_pass}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/liquibase/versions/01_orders.yaml

base.url.cart-microservice=http://cart:8421/api/cart

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

rabbit.exchange.invoice=invoice.exchange
rabbit.routing-key.invoice.create=invoice.create
